# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with new one
[character] # The name of the module we are configuring is "character"
success_symbol = "[λ](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
